name: .NET Core CI

on:
  push:
    branches: [ "main", "develop" ]
    paths-ignore:
      - '**.gitignore'
      - '**/README.md'
      - '**.dockerignore'
      - '**/stylecop.props'
      - '**/stylecop.ruleset'
      - '**/stylecop.json'
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore:
      - '**.gitignore'
      - '**/README.md'
      - '**.dockerignore'
      - '**/stylecop.props'
      - '**/stylecop.ruleset'
      - '**/stylecop.json'
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }} 

    defaults:
      run:
        shell: bash
        working-directory: menu-api
    strategy: 
      matrix: 
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.401

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
  sonarcloud:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: SonarCloud Scan
      run: cd menu-api
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  push:
    needs: [build_and_test, sonarcloud]
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./menu-api
    
    steps:

    - name: Login to DockerHub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/modus-1:menu-api